### ISSUE TITLE
Trailing comma breaks JSON parsing

### ISSUE THREAD

**Issue by chiphogg** [vincent-picaud/Bazel_and_CompileCommands#2]
YCM suddenly stopped working for me.  I tracked it down to a trailing comma in the JSON file.  Apparently, this can cause some implementations of JSON to fail to parse.

Fortunately, I was able to find and fix it without too much trouble.  It also cleans up a small part of the code.

**Comment by vincent-picaud** [comment]
Hi chiphogg,
Thank you very much for your feedback and work. Yes there are some problems with comma. I have incorporated your modification directly in the README.org file which automatically generates (Emacs tangling) the two sh scripts: setup_compile_command.sh and create_compile_compand.sh. -> That is the reason why I did not use your Pull Request that directly modify the setup_compile_command.sh file. Before closing this issue it would be great if you could check that my manual modification is conform to your PL and that everything is ok.
Best,
Vincent

**Comment by chiphogg** [comment]
Looks good to me, thanks!
