### ISSUE TITLE
Still working on this or seeking to move on?

### ISSUE THREAD

**Issue by cpsauer** [vincent-picaud/Bazel_and_CompileCommands#8]
Hi, @vincent-picaud!

Thanks so much for publishing this and your other guidance across the internet about getting compile commands from Bazel. They were instrumental in our transition to Bazel, and the tooling we built around it. Thank you!

After a bunch of experimentation with different approaches, we noticed that the relatively newer aquery interface let us directly dodge some of the issues with the action_listener approach--namely easy gathering of fresh outputs and fast generation that didn't require running a build--while still directly getting the commands Bazel intended use in a build.

Since its been a couple of years since last commit, and Bazel structure has changed a bit since, it looks like this repo might be one you've more or less moved on from. If that's wrong or annoyingly presumptuous--please ignore this next part. But if you'd be open to passing the torch, any chance you'd be willing to consider pointing people over to https://github.com/hedronvision/bazel-compile-commands-extractor in your README?  That repo was the culmination of our efforts on the aquery approach, and we actively use it every day.

I ask only because the author of the grailbio compile commands extractor [had asked us](https://github.com/grailbio/bazel-compilation-database/issues/57#issuecomment-973440644) to [file a PR along these lines](https://github.com/grailbio/bazel-compilation-database/pull/89), after coming across [the repo](https://github.com/hedronvision/bazel-compile-commands-extractor). That gave me a sense that it might be okay to reach out to you, who built one of the first great tools here, since you might be open to the request if you're ready to move on from maintaining this one.

Thanks so much for your consideration,
Chris

P.S. Saw your LinkedIn. Railguns and superconductors! Pretty cool stuff.

**Comment by vincent-picaud** [comment]
Hi @cpsauer,

Thank you for this kind report. I have no problem with what you said. It is correct that I am not using Bazel anymore and that I do not intend to upgrade my present script.

I have updated my README file according to this. I hope this is a clear and fair report of the situation.

Best,
Vincent

**Comment by cpsauer** [comment]
Definitely. Vincent, thanks for being open to it, for all you've done here, and for your care in helping others.

As an aside:
I think many users may find other options have issues that prevent their use. The question is how much to let them know vs explore for themselves. We certainly didn't set out to build one of these--we just wanted one that worked.

(Changes to Bazel structure have broken the older ones, commands need significant de-Bazeling for apple platforms, etc.. Happy to explain more if you'd like--took notes when trying them all out--but I will otherwise refrain.)

**Comment by vincent-picaud** [comment]
If you have any kind of information that can help users to make the good choice (comparison table...) feel free to propose a PR. This extra information can be added  in the "caveat & alternatives" section. 
Yes, It is a long time I haven't used Bazel and I imagine a lot have changed.
